version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=claroflex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    networks:
      - backend

  app:
    build: .
    image: guthubsearcher
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:

volumes:
  db-data: